import type { Project } from '../types/content';

export const projects: Project[] = [
  {
    image: '/images/projects/honn-me.png',
    title: 'honn.me',
    description: 'Book collection maker with dynamic Open Graph image.',
    stacks: [
      'Next.js',
      'NestJS',
      'Vercel',
      'Render',
      '@vercel/og',
      'Vitest',
      'Bunny.net',
    ],
    href: 'https://honn.me/',
  },
  {
    image: '/images/projects/yet-unresolved-xyz.png',
    title: 'yet.unresolved.xyz',
    description: 'This portfolio site.',
    stacks: ['Next.js', 'Vercel', 'Turborepo', 'Tailwind CSS'],
    href: 'https://yet.unresolved.xyz/',
    repositoryUrl:
      'https://github.com/dim0627/unresolved.xyz/tree/main/apps/yet',
  },
  {
    image: '/images/projects/blog-unresolved-xyz.png',
    title: 'blog.unresolved.xyz',
    description: 'Tech blog.',
    stacks: ['Next.js', 'Vercel', 'Turborepo', 'Tailwind CSS'],
    href: 'https://blog.unresolved.xyz/',
    repositoryUrl:
      'https://github.com/dim0627/unresolved.xyz/tree/main/apps/blog',
  },
  {
    image: '/images/projects/r0213-xyz.png',
    title: 'r0213.xyz',
    description:
      'Archive of fictional undelivered documents generated by an LLM.',
    stacks: ['Astro', 'Vercel', 'OpenAI', 'Anthropic', 'Vitest'],
    href: 'https://r0213.xyz/',
  },
  {
    image: '/images/projects/nutry-co.png',
    title: 'nutry.co',
    description: 'Q&A service for registered dietitians.',
    stacks: ['Ruby on Rails'],
    closed: true,
  },
  {
    image: '/images/projects/p-and-ora-me.png',
    title: 'p-and-ora.me',
    description: 'Entertainment content curation platform.',
    stacks: ['Hugo', 'Netlify'],
    closed: true,
  },
  {
    image: '/images/projects/snowdo-me.png',
    title: 'snowdo.me',
    description: 'Aggregated ski resort search engine.',
    stacks: ['Ruby on Rails'],
    closed: true,
  },
  {
    image: '/images/projects/recr-biz.png',
    title: 'RECR',
    description: 'Matching service for employees and employers.',
    stacks: ['Ruby on Rails'],
    closed: true,
  },
];
