name: Labeling from branch name

on:
  pull_request:
    types: [opened]

jobs:
  main:
    name: Labeling from branch name
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/pr-labeler.yml # optionalだが、どのワークフローから使われているのか明示したいので記述しておく
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
